# Generated by Django 5.0.5 on 2024-06-08 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0011_auto_20200612_1455"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dztable",
            name="psw",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="jstable",
            name="dzid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="myWEB.dztable"
            ),
        ),
        migrations.AlterField(
            model_name="jstable",
            name="tsid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="myWEB.tstable"
            ),
        ),
        migrations.AlterField(
            model_name="tsglytable",
            name="psw",
            field=models.CharField(max_length=256),
        ),
    ]
