# Generated by Django 5.0.5 on 2024-06-08 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0012_alter_dztable_psw_alter_jstable_dzid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dztable",
            name="email",
        ),
    ]
