# Generated by Django 5.0.5 on 2024-06-09 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0013_remove_dztable_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dztable",
            name="dh",
        ),
    ]
