# Generated by Django 5.0.5 on 2024-06-09 03:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0014_remove_dztable_dh"),
    ]

    operations = [
        migrations.DeleteModel(
            name="yyTable",
        ),
    ]
