# Generated by Django 5.0.5 on 2024-06-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0015_delete_yytable"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtable",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
