# Generated by Django 5.0.5 on 2024-06-10 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0016_smtable_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tsglytable",
            old_name="gh",
            new_name="glyid",
        ),
    ]
