# Generated by Django 5.0.5 on 2024-06-18 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0018_jstable_is_valid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smtable",
            name="jbr",
        ),
    ]
