# Generated by Django 5.0.5 on 2024-06-19 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0019_remove_smtable_jbr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jstable",
            name="tsid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myWEB.tstable",
            ),
        ),
    ]
