# Generated by Django 5.0.5 on 2024-06-28 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0021_bookreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookreview",
            name="created_at",
        ),
        migrations.AddField(
            model_name="bookreview",
            name="comment_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
