# Generated by Django 5.0.5 on 2024-07-20 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myWEB", "0023_alter_bookreview_isbn"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookreview",
            unique_together={("dzid", "isbn")},
        ),
    ]
